openapi: 3.0.1
info:
  title: API vigilsanbuonores
  description: Componente API vigilsanbuonores del prodotto vigilsan
  version: 1.0.0
servers:
  - url: /api
paths:
  /status:
    get:
      tags:
        - system
      description: ping
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                type: string
components:
  schemas:
    boolean_crit:
      type: object
      properties:
        eq:
          type: boolean
    string_crit:
      type: object
      properties:
        eq:
          type: string
        ne:
          type: string
        lt:
          type: string
        lte:
          type: string
        gt:
          type: string
        gte:
          type: string
        in:
          type: array
          items:
            type: string
        nin:
          type: array
          items:
            type: string
        c:
          type: string
        ci:
          type: string
        s:
          type: string
        si:
          type: string
        e:
          type: string
        ei:
          type: string
      description: criterio su singola property di tipo stringa
    integer_crit:
      type: object
      properties:
        eq:
          type: integer
          format: int32
        ne:
          type: integer
          format: int32
        lt:
          type: integer
          format: int32
        lte:
          type: integer
          format: int32
        gt:
          type: integer
          format: int32
        gte:
          type: integer
          format: int32
        in:
          type: array
          items:
            type: integer
            format: int32
        nin:
          type: array
          items:
            type: integer
            format: int32
      description: criterio su singola property di tipo integer
    date_crit:
      type: object
      properties:
        eq:
          type: string
          format: date
        ne:
          type: string
          format: date
        lt:
          type: string
          format: date
        lte:
          type: string
          format: date
        gt:
          type: string
          format: date
        gte:
          type: string
          format: date
        in:
          type: array
          items:
            type: string
            format: date
        nin:
          type: array
          items:
            type: string
            format: date
      description: criterio su singola property di tipo data
    Error:
      type: object
      properties:
        code:
          type: string
        messaggioCittadino:
          type: string
        errorMessage:
          type: string
        fields:
          type: string
          nullable: true