openapi: 3.0.1
info:
  title: API VIGILSANBATCHSRV
  description: Componente API  VIGILSANBATCHSRV del prodotto VIGILSAN
  version: 1.0.0
servers:
  - url: /api
paths:
  /rpviar:
    post:
      operationId: funzionalita_batchRpviarPost
      tags:
        - batch
      description: aggiorna le strutture dai dati forniti da arpe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model_input_file_information'
      responses:
        "200":
          description: OK
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /estrazione/rilevazioni:
    post:
      operationId: funzionalita_batchEstrazioniRilevazionePost
      tags:
        - batch
      description: aggiorna le viste delle rilevazioni
      responses:
        "204":
          description: No Content
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /rpvini:
    post:
      operationId: funzionalita_batchInvioNotifysanPost
      tags:
        - batch
      description: invio notifiche agli operatori sanitari
      responses:
        "204":
          description: No Content
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /rpvinv:
    post:
      operationId: funzionalita_batchVerificaNotifysanPost
      tags:
        - batch
      description: verifica notifiche agli operatori sanitari
      responses:
        "204":
          description: No Content
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    header_content_type:
      description: MIME Type del file che viene caricato come allegato
      name: Content-Type
      in: header
      schema:
        type: string
        enum:
          - document/pdf
          - image/jpeg
          - image/png 
    header_shib_identita_codice_fiscale:
      description: Contiene il codice fiscale dell utente loggato ottenuto tramite shibboleth
      name: Shib-Identita-CodiceFiscale
      in: header
      schema:
        type: string
      required: true
    header_x_request_id:
      description: Contiene un id univoco (`uuid v4`) della chiamata HTTP che viene generato dal front-end, viene propagato agli strati successivi e viene restituito al front-end assieme alla response, permettendo così di tracciare l intero ciclo di vita della richiesta
      in: header
      name: X-Request-Id      
      schema:
        type: string
      required: true
    header_x_forwarded_for:
      description: Contiene un elenco degli ip che hanno gestito la richiesta.Utile per log e audit.Il formato della stringa è <ip-front-end>, <ip-primo-server>, ..., <ip-ultimo-server> Es. `10.10.10.10, 10.38.45.68, 10.128.69.244`
      in: header
      name: X-Forwarded-For      
      schema:
        type: string
      required: true
    header_x_codice_servizio:
      in: header
      name: X-Codice-Servizio    
      description: Contiene una stringa identificativa del servizio chiamante (es.COD)
      schema:
        type: string
      required: true
  responses:
    BadRequest:
      description: La richiesta fatta dal client è errata.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errore'
      headers:
        X-Request-ID:
          description: Ritorno del parametro ricevuto nella request.
          schema:
            type: string  
    Forbidden:
      description: La richiesta fatta dal client è errata.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errore'
      headers:
        X-Request-ID:
          description: Ritorno del parametro ricevuto nella request.
          schema:
            type: string              
    NotFound:
      description: La richiesta fatta dal client errata.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errore'
      headers:
        X-Request-ID:
          description: Ritorno del parametro ricevuto nella request.
          schema:
            type: string
    InternalServerError:
      description: La richiesta fatta dal client errata.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errore'
      headers:
        X-Request-ID:
          description: Ritorno del parametro ricevuto nella request.
          schema:
            type: string
  schemas:
    boolean_crit:
      type: object
      properties:
        eq:
          type: boolean
    string_crit:
      type: object
      properties:
        eq:
          type: string
        ne:
          type: string
        lt:
          type: string
        lte:
          type: string
        gt:
          type: string
        gte:
          type: string
        in:
          type: array
          items:
            type: string
        nin:
          type: array
          items:
            type: string
        c:
          type: string
        ci:
          type: string
        s:
          type: string
        si:
          type: string
        e:
          type: string
        ei:
          type: string
      description: criterio su singola property di tipo stringa
    integer_crit:
      type: object
      properties:
        eq:
          type: integer
          format: int32
        ne:
          type: integer
          format: int32
        lt:
          type: integer
          format: int32
        lte:
          type: integer
          format: int32
        gt:
          type: integer
          format: int32
        gte:
          type: integer
          format: int32
        in:
          type: array
          items:
            type: integer
            format: int32
        nin:
          type: array
          items:
            type: integer
            format: int32
      description: criterio su singola property di tipo integer
    date_crit:
      type: object
      properties:
        eq:
          type: string
          format: date
        ne:
          type: string
          format: date
        lt:
          type: string
          format: date
        lte:
          type: string
          format: date
        gt:
          type: string
          format: date
        gte:
          type: string
          format: date
        in:
          type: array
          items:
            type: string
            format: date
        nin:
          type: array
          items:
            type: string
            format: date
      description: criterio su singola property di tipo data
    model_input_file_information:
      type: object
      properties:
        pathFile:
          type: string
    errore:
      title: '[ERRORE] Generico'
      type: object
      properties:
        status:
          type: integer
        code:
          type: string
        title:
          type: string
        detail:
          type: array
          items:
            $ref: '#/components/schemas/errore_dettaglio'
        links:
          type: array
          items:
            type: string
    errore_dettaglio:
      title: '[ERRORE] Dettaglio'
      type: object
      properties:
        chiave:
          type: string
        valore:
          type: string  
    Error:
      type: object
      properties:
        code:
          type: string
        messaggioCittadino:
          type: string
        errorMessage:
          type: string
        fields:
          type: string
          nullable: true
