/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.vigilsan.vigilsanpratiche.util;

import it.csi.vigilsan.vigilsanutil.generic.services.error.ErrorCodeInterface;
import jakarta.ws.rs.core.Response.Status;

public enum ErrorCodeEnum implements ErrorCodeInterface {

	INTERNAL_SERVER_ERROR("VIGILSANPRATICHE_1", ErrorMessageEnum.INTERNAL_SERVER_ERROR, Status.INTERNAL_SERVER_ERROR),
	ENTE_ID_OBBLIGATORIO("VIGILSANPRATICHE_2", ErrorMessageEnum.ENTE_ID_OBBLIGATORIO),
	PRATICA_TIPO_ID_OBBLIGATORIO("VIGILSANPRATICHE_3", ErrorMessageEnum.PRATICA_TIPO_ID_OBBLIGATORIO),
	STRUTTURA_TIPO_ID_OBBLIGATORIO("VIGILSANPRATICHE_4", ErrorMessageEnum.STRUTTURA_TIPO_ID_OBBLIGATORIO),
	ERRORE_CREAZIONE_OGGETTO_QUERY("VIGILSANPRATICHE_5", ErrorMessageEnum.ERRORE_CREAZIONE_OGGETTO_QUERY,
			Status.INTERNAL_SERVER_ERROR),
	PRATICA_TIPO_NON_TROVATA("VIGILSANPRATICHE_6", ErrorMessageEnum.PRATICA_TIPO_NON_TROVATA),
	AZIONE_NON_TROVATA("VIGILSANPRATICHE_7", ErrorMessageEnum.AZIONE_NON_TROVATA),
	ERRORE_INSERIMENTO_PRATICA("VIGILSANPRATICHE_8", ErrorMessageEnum.ERRORE_INSERIMENTO_PRATICA),
	ERRORE_INSERIMENTO_PRATICA_DETTAGLIO("VIGILSANPRATICHE_9", ErrorMessageEnum.ERRORE_INSERIMENTO_PRATICA_DETTAGLIO),
	DATA_DA_OBBLIGATORIA("VIGILSANPRATICHE_10", ErrorMessageEnum.DATA_DA_OBBLIGATORIA),
	DATA_A_OBBLIGATORIA("VIGILSANPRATICHE_11", ErrorMessageEnum.DATA_A_OBBLIGATORIA),
	PRATICA_ID_OBBLIGATORIA("VIGILSANPRATICHE_12", ErrorMessageEnum.PRATICA_ID_OBBLIGATORIA),
	PRATICA_NON_TROVATA_ENTE("VIGILSANPRATICHE_13", ErrorMessageEnum.PRATICA_NON_TROVATA),
	PRATICA_NON_TROVATA_STRUTTURA("VIGILSANPRATICHE_14", ErrorMessageEnum.PRATICA_NON_TROVATA),
	PRATICA_INSERIMENTO_NON_ABILITATA("VIGILSANPRATICHE_15", ErrorMessageEnum.PRATICA_INSERIMENTO_NON_ABILITATA),
	AZIONE_ATTIVITA_DIVERSA("VIGILSANPRATICHE_16", ErrorMessageEnum.AZIONE_ATTIVITA_DIVERSA),
	AZIONE_NON_ABILITATO_INSMOD("VIGILSANPRATICHE_17", ErrorMessageEnum.AZIONE_NON_ABILITATO_INSMOD),
	AZIONE_ATTIVITA_NON_TROVATA("VIGILSANPRATICHE_18", ErrorMessageEnum.AZIONE_ATTIVITA_NON_TROVATA),
	AZIONE_NON_ABILITATO_SCADENZE_AUTOMATICHE("VIGILSANPRATICHE_19",
			ErrorMessageEnum.AZIONE_NON_ABILITATO_SCADENZE_AUTOMATICHE),
	AZIONE_PROFILO_NON_ABILITATO("VIGILSANPRATICHE_20", ErrorMessageEnum.AZIONE_PROFILO_NON_ABILITATO),
	PRATICA_TIPO_ID_UGUALE("VIGILSANPRATICHE_21", ErrorMessageEnum.PRATICA_TIPO_ID_UGUALE),
	SECONDA_NUOVA_PRATICA("VIGILSANPRATICHE_22", ErrorMessageEnum.SECONDA_NUOVA_PRATICA),
	PRATICA_ID_NULL("VIGILSANPRATICHE_23", ErrorMessageEnum.PRATICA_ID_NULL),
	PRESCRIZIONE_ASSOCIATA_NON_TROVATA("VIGILSANPRATICHE_24", ErrorMessageEnum.PRESCRIZIONE_ASSOCIATA_NON_TROVATA),
	ATTIVITA_SOPRALLUOGO_GENEREREREBBE_PRESCRIZIONE("VIGILSANPRATICHE_25",
			ErrorMessageEnum.ATTIVITA_SOPRALLUOGO_GENEREREREBBE_PRESCRIZIONE),
	ATTIVITA_SECONDA_PRESCRIZIONE("VIGILSANPRATICHE_26", ErrorMessageEnum.ATTIVITA_SECONDA_PRESCRIZIONE),
	ATTIVITA_NON_COMPATIBILE_PRESCRIZIONE("VIGILSANPRATICHE_27",
			ErrorMessageEnum.ATTIVITA_NON_COMPATIBILE_PRESCRIZIONE),
	ATTIVITA_NON_COMPATIBILE_PRESCRIZIONE_STATO("VIGILSANPRATICHE_28",
			ErrorMessageEnum.ATTIVITA_NON_COMPATIBILE_PRESCRIZIONE_STATO),
	ATTIVITA_SOPRALLUOGO_SCONOSCIUTO("VIGILSANPRATICHE_29", ErrorMessageEnum.ATTIVITA_SOPRALLUOGO_SCONOSCIUTO),
	ATTIVITA_GENERA_UN_SOPRALLUOGO("VIGILSANPRATICHE_30", ErrorMessageEnum.ATTIVITA_GENERA_UN_SOPRALLUOGO),
	ATTIVITA_GENERA_SECONDO_SOPRALLUOGO("VIGILSANPRATICHE_31", ErrorMessageEnum.ATTIVITA_GENERA_SECONDO_SOPRALLUOGO),
	ATTIVITA_GENERA_SOPRALLUOGO_NO_ORA_INIZIO("VIGILSANPRATICHE_32",
			ErrorMessageEnum.ATTIVITA_GENERA_SOPRALLUOGO_NO_ORA_INIZIO),
	ATTIVITA_GENERA_SOPRALLUOGO_NO_ORA_FINE("VIGILSANPRATICHE_33",
			ErrorMessageEnum.ATTIVITA_GENERA_SOPRALLUOGO_NO_ORA_FINE),
	ATTIVITA_GENERA_SOPRALLUOGO_DIVERSO("VIGILSANPRATICHE_34", ErrorMessageEnum.ATTIVITA_GENERA_SOPRALLUOGO_DIVERSO),
	ATTIVITA_ASSOCITANA_NON_APERTA("VIGILSANPRATICHE_35", ErrorMessageEnum.ATTIVITA_ASSOCITANA_NON_APERTA),
	SOPRALLUOGO_NON_COMPATIBILE("VIGILSANPRATICHE_36", ErrorMessageEnum.SOPRALLUOGO_NON_COMPATIBILE),
	ATTIVITA_NON_COMATIBILE_CON_SOPRALLUOGO("VIGILSANPRATICHE_37",
			ErrorMessageEnum.ATTIVITA_NON_COMATIBILE_CON_SOPRALLUOGO),
	ATTIVITA_NON_COMATIBILE_CON_SOPRALLUOGO_STATO("VIGILSANPRATICHE_38",
			ErrorMessageEnum.ATTIVITA_NON_COMATIBILE_CON_SOPRALLUOGO_STATO),
	ATTIVITA_NON_COMPATIBILE_PRATICA_CHIUSA("VIGILSANPRATICHE_39",
			ErrorMessageEnum.ATTIVITA_NON_COMPATIBILE_PRATICA_CHIUSA),
	ATTIVITA_NON_COMPATIBILE_PRATICA_STATO("VIGILSANPRATICHE_40",
			ErrorMessageEnum.ATTIVITA_NON_COMPATIBILE_PRATICA_STATO),
	ATTIVITA_NON_PUO_CAMBIARE_STATO("VIGILSANPRATICHE_41", ErrorMessageEnum.ATTIVITA_NON_PUO_CAMBIARE_STATO),
	ATTIVITA_PRATICA_CON_SOPRALLUOGO("VIGILSANPRATICHE_42", ErrorMessageEnum.ATTIVITA_PRATICA_CON_SOPRALLUOGO),
	ATTIVITA_GENERA_PRESCRIZIONE_DIVERSA("VIGILSANPRATICHE_43", ErrorMessageEnum.ATTIVITA_GENERA_PRESCRIZIONE_DIVERSA),
	ATTIVITA_NON_ASSOCIATA_PRESCRIZIONE("VIGILSANPRATICHE_44", ErrorMessageEnum.ATTIVITA_NON_ASSOCIATA_PRESCRIZIONE),
	PRESCRIZIONE_NON_COMPATIBILE("VIGILSANPRATICHE_45", ErrorMessageEnum.PRESCRIZIONE_NON_COMPATIBILE),
	PRATICA_TIPO_ID_NON_TROVATA("VIGILSANPRATICHE_46", ErrorMessageEnum.PRATICA_TIPO_ID_NON_TROVATA),
	PRATICA_DETTAGLIO_NON_TROVATA("VIGILSANPRATICHE_47", ErrorMessageEnum.PRATICA_DETTAGLIO_NON_TROVATA),
	AZIONE_ID_NON_TROVATA("VIGILSANPRATICHE_48", ErrorMessageEnum.AZIONE_ID_NON_TROVATA),
	DATA_ORA_AZIONE_NON_TROVATA("VIGILSANPRATICHE_49", ErrorMessageEnum.DATA_ORA_AZIONE_NON_TROVATA),
	UTENTE_NON_ABILITATO_PER_SCADENZE_AUTOMATICHE("VIGILSANPRATICHE_50",
			ErrorMessageEnum.UTENTE_NON_ABILITATO_PER_SCADENZE_AUTOMATICHE),
	FLAG_SCADENZA_NON_TROVATO("VIGILSANPRATICHE_51", ErrorMessageEnum.FLAG_SCADENZA_NON_TROVATO),
	PRATICA_DET_ID_OBBLIGATORIO("VIGILSANPRATICHE_52", ErrorMessageEnum.PRATICA_DET_ID_OBBLIGATORIO),
	UTENTE_NON_ABILITATO_INSERIMENTO("VIGILSANPRATICHE_53", ErrorMessageEnum.UTENTE_NON_ABILITATO_INSERIMENTO),
	ATTIVITA_GENEREREBBE_NUOVA_PRESCRIIONE("VIGILSANPRATICHE_54",
			ErrorMessageEnum.ATTIVITA_GENEREREBBE_NUOVA_PRESCRIIONE),
	DATA_ORA_AZIONE_NEL_FUTURO("VIGILSANPRATICHE_50", ErrorMessageEnum.DATA_ORA_AZIONE_NEL_FUTURO),
	PAYLOAD_OBBLIGATORIO("VIGILSANPRATICHE_51", ErrorMessageEnum.PAYLOAD_OBBLIGATORIO),
	APPUNTAMENTO_ID_OBBLIGATORIO("VIGILSANPRATICHE_52", ErrorMessageEnum.APPUNTAMENTO_ID_OBBLIGATORIO),
	SOGGETTO_ID_OBBLIGATORIO("VIGILSANPRATICHE_53", ErrorMessageEnum.SOGGETTO_ID_OBBLIGATORIO),
	APPUNTAMENTO_SOGGETTO_ID_OBBLIGATORIO("VIGILSANPRATICHE_54",
			ErrorMessageEnum.APPUNTAMENTO_SOGGETTO_ID_OBBLIGATORIO),
	APPUNTAMENTO_SOGGETTO_NON_VALIDO("VIGILSANPRATICHE_55", ErrorMessageEnum.APPUNTAMENTO_SOGGETTO_NON_VALIDO),
	APPUNTAMENTO_SOGGETTO_ASSOCIAZIONE_NON_VALIDA("VIGILSANPRATICHE_56",
			ErrorMessageEnum.APPUNTAMENTO_SOGGETTO_ASSOCIAZIONE_NON_VALIDA),
	APPUNTAMENTO_SOGGETTO_ASSOCIAZIONE_ESISTENTE("VIGILSANPRATICHE_57",
			ErrorMessageEnum.APPUNTAMENTO_SOGGETTO_ASSOCIAZIONE_ESISTENTE),
	AZIONE_INIZIALE_NON_TROVATA("VIGILSANPRATICHE_58", ErrorMessageEnum.AZIONE_INIZIALE_NON_TROVATA),
	CLREQ_ID_OBBLIGATORIO("VIGILSANPRATICHE_59", ErrorMessageEnum.CLREQ_ID_OBBLIGATORIO),

	;

	private final String code;
	private final String message;
	private final Status status;

	private ErrorCodeEnum(String code, ErrorMessageEnum messageEnum) {
		this.code = code;
		this.message = messageEnum.getMessage();
		this.status = Status.BAD_REQUEST;
	}

	ErrorCodeEnum(String code, ErrorMessageEnum messageEnum, Status status) {
		this.code = code;
		this.message = messageEnum.getMessage();
		this.status = status;
	}

	@Override
	public String getCode() {
		return code;
	}

	@Override
	public String getMessage() {
		return message;
	}

	@Override
	public Status getStatus() {
		return status;
	}

}